package token

type TokenKind int
const (
    TOKEN_OPEN_PAREN = iota
    TOKEN_CLOSE_PAREN
    TOKEN_OPEN_CURLY
    TOKEN_CLOSE_CURLY
    TOKEN_OPEN_BRACKET
    TOKEN_CLOSE_BRACKET
    TOKEN_SEMICOLON
    TOKEN_COMMA
    TOKEN_OPERATOR
    TOKEN_ASTERISK
    TOKEN_NUMBER
    TOKEN_SYMBOL
    TOKEN_KEYWORD
    TOKEN_COMMENT
    TOKEN_OPEN_MULTICOMMENT
    TOKEN_CLOSE_MULTICOMMENT
)

type Token struct {
    Kind TokenKind
    Value string
}
